// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwsS5Ni8uf-XbuPCA2f84bwIKm_igmFR4',
    appId: '1:806835138328:web:f735570d32e8455a45f86d',
    messagingSenderId: '806835138328',
    projectId: 'savelife-6c137',
    authDomain: 'savelife-6c137.firebaseapp.com',
    storageBucket: 'savelife-6c137.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC41xk354iP6Km_eIrNYdkvKsz_blRBdKM',
    appId: '1:806835138328:android:12db14a3f3c19c9845f86d',
    messagingSenderId: '806835138328',
    projectId: 'savelife-6c137',
    storageBucket: 'savelife-6c137.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYv_lC5reFXl18R-g7R4-Kmkv9Yr-93iA',
    appId: '1:806835138328:ios:14742dd8e7d56d6645f86d',
    messagingSenderId: '806835138328',
    projectId: 'savelife-6c137',
    storageBucket: 'savelife-6c137.firebasestorage.app',
    iosBundleId: 'com.example.savelife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYv_lC5reFXl18R-g7R4-Kmkv9Yr-93iA',
    appId: '1:806835138328:ios:14742dd8e7d56d6645f86d',
    messagingSenderId: '806835138328',
    projectId: 'savelife-6c137',
    storageBucket: 'savelife-6c137.firebasestorage.app',
    iosBundleId: 'com.example.savelife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwsS5Ni8uf-XbuPCA2f84bwIKm_igmFR4',
    appId: '1:806835138328:web:33fe8b2ce832f02445f86d',
    messagingSenderId: '806835138328',
    projectId: 'savelife-6c137',
    authDomain: 'savelife-6c137.firebaseapp.com',
    storageBucket: 'savelife-6c137.firebasestorage.app',
  );
}
